"""Diff Cinema — HTML narrative export."""

from __future__ import annotations

import html
from datetime import datetime

from peekaboo.schemas import CveDetails, PoCBlueprint, Report


def render_cinema(
    details: CveDetails | None,
    report: Report,
    poc: PoCBlueprint | None = None,
) -> str:
    cb = report.confidence_breakdown
    conf_bars = _bar(cb.component_match) + " component match<br>"
    conf_bars += _bar(cb.function_diff) + " function change<br>"
    conf_bars += _bar(cb.decompile_quality) + " decompile quality<br>"
    conf_bars += _bar(cb.re_backend_quality) + " RE backend<br>"
    conf_bars += _bar(cb.llm_assessment) + " LLM assessment<br>"

    poc_section = ""
    if poc:
        steps = "".join(f"<li>{html.escape(s)}</li>" for s in poc.reproduction_steps)
        limits = "".join(f"<li>{html.escape(l)}</li>" for l in poc.limitations)
        poc_section = f"""
        <section>
          <h2>PoC Blueprint — {html.escape(poc.title)}</h2>
          <p><strong>Hypothesis:</strong> {html.escape(poc.hypothesis)}</p>
          <p><strong>Attack vector:</strong> {html.escape(poc.attack_vector)}</p>
          <p><strong>Trigger surface:</strong> {html.escape(poc.trigger_surface)}</p>
          <p><strong>PoC confidence:</strong> {poc.poc_confidence:.2f}</p>
          <h3>Reproduction steps</h3>
          <ol>{steps}</ol>
          <h3>Verification signals</h3>
          <ul>{''.join(f'<li>{html.escape(v)}</li>' for v in poc.verification_signals)}</ul>
          <h3>Minimal code ({html.escape(poc.language)})</h3>
          <pre><code>{html.escape(poc.minimal_code)}</code></pre>
          <h3>Limitations</h3>
          <ul>{limits}</ul>
        </section>
        """

    adv = details or CveDetails(cve=report.cve, platform=report.platform)
    review_badge = (
        '<span class="badge warn">Human review recommended</span>'
        if cb.human_review_recommended
        else '<span class="badge ok">Evidence coherent</span>'
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>Peekaboo — {html.escape(report.cve)}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 920px; margin: 2rem auto; padding: 0 1rem; background: #0d1117; color: #e6edf3; }}
    h1 {{ color: #58a6ff; }}
    h2 {{ border-bottom: 1px solid #30363d; padding-bottom: 0.3rem; }}
    pre {{ background: #161b22; padding: 1rem; overflow-x: auto; border-radius: 6px; }}
    .badge {{ padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.85rem; }}
    .badge.warn {{ background: #9e6a03; }}
    .badge.ok {{ background: #238636; }}
    .meta {{ color: #8b949e; }}
    .bar {{ display: inline-block; height: 8px; background: #238636; border-radius: 2px; }}
    section {{ margin: 2rem 0; }}
  </style>
</head>
<body>
  <h1>{html.escape(report.cve)}</h1>
  <p class="meta">Platform: {html.escape(report.platform)} · {html.escape(report.file_name)} · {html.escape(report.function_name)}</p>
  <p>{review_badge} Overall confidence: <strong>{cb.overall:.2f}</strong></p>

  <section>
    <h2>Confidence breakdown</h2>
    {conf_bars}
    <ul>{''.join(f'<li>{html.escape(n)}</li>' for n in cb.notes)}</ul>
  </section>

  <section>
    <h2>Advisory</h2>
    <p><strong>Component:</strong> {html.escape(adv.component or "—")}</p>
    <p><strong>Impact:</strong> {html.escape(adv.impact or "—")}</p>
    <p>{html.escape(adv.description or "")}</p>
  </section>

  <section>
    <h2>Root cause analysis</h2>
    <p>{html.escape(report.summary)}</p>
    <details>
      <summary>Full analysis</summary>
      <pre>{html.escape(report.root_cause)}</pre>
    </details>
  </section>

  <section>
    <h2>Patch diff</h2>
    <pre>{html.escape(report.diff_text or "(none)")}</pre>
  </section>

  {poc_section}

  <footer class="meta">Generated by Peekaboo · {datetime.utcnow().isoformat()}Z</footer>
</body>
</html>"""


def _bar(score: float, width: int = 120) -> str:
    w = int(score * width)
    return f'<span class="bar" style="width:{w}px"></span> {score:.2f}'
